-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Fertilizantes
create table public.fertilizantes (
  id bigint generated by default as identity primary key,
  nome text not null,
  formulacao text, -- Ex: 20-00-20
  cultura_indicada text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Precos
create table public.precos (
  id bigint generated by default as identity primary key,
  id_fertilizante bigint references public.fertilizantes(id) on delete cascade,
  valor numeric not null,
  moeda text default 'BRL',
  unidade text default 'Ton',
  origem text, -- Ex: Heringer Manhuaçu
  data_cotacao timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Indicadores (Dólar, Ureia, etc.)
create table public.indicadores (
  id bigint generated by default as identity primary key,
  nome text not null, -- Ex: Dólar, Ureia CME
  valor numeric not null,
  unidade text, -- Ex: BRL, USD/Ton
  fonte text,
  data_referencia timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Previsoes
create table public.previsoes (
  id bigint generated by default as identity primary key,
  id_fertilizante bigint references public.fertilizantes(id) on delete cascade,
  tendencia text check (tendencia in ('alta', 'baixa', 'estavel')),
  justificativa text,
  nivel_confianca integer, -- 0 a 100
  data_previsao timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Security)
alter table public.fertilizantes enable row level security;
alter table public.precos enable row level security;
alter table public.indicadores enable row level security;
alter table public.previsoes enable row level security;

-- Public read access for now
create policy "Public read access fertilizantes" on public.fertilizantes for select using (true);
create policy "Public read access precos" on public.precos for select using (true);
create policy "Public read access indicadores" on public.indicadores for select using (true);
create policy "Public read access previsoes" on public.previsoes for select using (true);
